//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsApp.Visits {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Visits.IVisitsService")]
    public interface IVisitsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/SaveVisit", ReplyAction="http://tempuri.org/IVisitsService/SaveVisitResponse")]
        string SaveVisit(string uid, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/SaveVisit", ReplyAction="http://tempuri.org/IVisitsService/SaveVisitResponse")]
        System.Threading.Tasks.Task<string> SaveVisitAsync(string uid, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetAllVisits", ReplyAction="http://tempuri.org/IVisitsService/GetAllVisitsResponse")]
        string GetAllVisits(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetAllVisits", ReplyAction="http://tempuri.org/IVisitsService/GetAllVisitsResponse")]
        System.Threading.Tasks.Task<string> GetAllVisitsAsync(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetPageVisits", ReplyAction="http://tempuri.org/IVisitsService/GetPageVisitsResponse")]
        string GetPageVisits(string uid, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetPageVisits", ReplyAction="http://tempuri.org/IVisitsService/GetPageVisitsResponse")]
        System.Threading.Tasks.Task<string> GetPageVisitsAsync(string uid, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetPageVisitsByDate", ReplyAction="http://tempuri.org/IVisitsService/GetPageVisitsByDateResponse")]
        string GetPageVisitsByDate(string uid, string pid, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetPageVisitsByDate", ReplyAction="http://tempuri.org/IVisitsService/GetPageVisitsByDateResponse")]
        System.Threading.Tasks.Task<string> GetPageVisitsByDateAsync(string uid, string pid, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetPageVisitsByWeek", ReplyAction="http://tempuri.org/IVisitsService/GetPageVisitsByWeekResponse")]
        string GetPageVisitsByWeek(string uid, string pid, string week);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitsService/GetPageVisitsByWeek", ReplyAction="http://tempuri.org/IVisitsService/GetPageVisitsByWeekResponse")]
        System.Threading.Tasks.Task<string> GetPageVisitsByWeekAsync(string uid, string pid, string week);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisitsServiceChannel : AnalyticsApp.Visits.IVisitsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitsServiceClient : System.ServiceModel.ClientBase<AnalyticsApp.Visits.IVisitsService>, AnalyticsApp.Visits.IVisitsService {
        
        public VisitsServiceClient() {
        }
        
        public VisitsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveVisit(string uid, string pid) {
            return base.Channel.SaveVisit(uid, pid);
        }
        
        public System.Threading.Tasks.Task<string> SaveVisitAsync(string uid, string pid) {
            return base.Channel.SaveVisitAsync(uid, pid);
        }
        
        public string GetAllVisits(string uid) {
            return base.Channel.GetAllVisits(uid);
        }
        
        public System.Threading.Tasks.Task<string> GetAllVisitsAsync(string uid) {
            return base.Channel.GetAllVisitsAsync(uid);
        }
        
        public string GetPageVisits(string uid, string pid) {
            return base.Channel.GetPageVisits(uid, pid);
        }
        
        public System.Threading.Tasks.Task<string> GetPageVisitsAsync(string uid, string pid) {
            return base.Channel.GetPageVisitsAsync(uid, pid);
        }
        
        public string GetPageVisitsByDate(string uid, string pid, string date) {
            return base.Channel.GetPageVisitsByDate(uid, pid, date);
        }
        
        public System.Threading.Tasks.Task<string> GetPageVisitsByDateAsync(string uid, string pid, string date) {
            return base.Channel.GetPageVisitsByDateAsync(uid, pid, date);
        }
        
        public string GetPageVisitsByWeek(string uid, string pid, string week) {
            return base.Channel.GetPageVisitsByWeek(uid, pid, week);
        }
        
        public System.Threading.Tasks.Task<string> GetPageVisitsByWeekAsync(string uid, string pid, string week) {
            return base.Channel.GetPageVisitsByWeekAsync(uid, pid, week);
        }
    }
}
