//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsApp.Sites {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfUsers5pAuinzC", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class ResponseOfUsers5pAuinzC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Sites.Error errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Sites.Users[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AnalyticsApp.Sites.Error error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AnalyticsApp.Sites.Users[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.display_nameField, value) != true)) {
                    this.display_nameField = value;
                    this.RaisePropertyChanged("display_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Guid user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfSites5pAuinzC", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class ResponseOfSites5pAuinzC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Sites.Error errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Sites.Sites[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AnalyticsApp.Sites.Error error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AnalyticsApp.Sites.Sites[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sites", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class Sites : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Sites.Users UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Sites.Visits[] VisitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnalyticsApp.Sites.Users Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnalyticsApp.Sites.Visits[] Visits {
            get {
                return this.VisitsField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitsField, value) != true)) {
                    this.VisitsField = value;
                    this.RaisePropertyChanged("Visits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visits", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class Visits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string call_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exit_timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string call_time {
            get {
                return this.call_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.call_timeField, value) != true)) {
                    this.call_timeField = value;
                    this.RaisePropertyChanged("call_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string exit_time {
            get {
                return this.exit_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.exit_timeField, value) != true)) {
                    this.exit_timeField = value;
                    this.RaisePropertyChanged("exit_time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sites.ISitesService")]
    public interface ISitesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Save", ReplyAction="http://tempuri.org/ISitesService/SaveResponse")]
        AnalyticsApp.Sites.ResponseOfUsers5pAuinzC Save(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Save", ReplyAction="http://tempuri.org/ISitesService/SaveResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfUsers5pAuinzC> SaveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/GetAll", ReplyAction="http://tempuri.org/ISitesService/GetAllResponse")]
        AnalyticsApp.Sites.ResponseOfSites5pAuinzC GetAll(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/GetAll", ReplyAction="http://tempuri.org/ISitesService/GetAllResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfSites5pAuinzC> GetAllAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Get", ReplyAction="http://tempuri.org/ISitesService/GetResponse")]
        AnalyticsApp.Sites.ResponseOfSites5pAuinzC Get(string id, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Get", ReplyAction="http://tempuri.org/ISitesService/GetResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfSites5pAuinzC> GetAsync(string id, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Update", ReplyAction="http://tempuri.org/ISitesService/UpdateResponse")]
        AnalyticsApp.Sites.ResponseOfSites5pAuinzC Update(string id, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Update", ReplyAction="http://tempuri.org/ISitesService/UpdateResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfSites5pAuinzC> UpdateAsync(string id, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Remove", ReplyAction="http://tempuri.org/ISitesService/RemoveResponse")]
        AnalyticsApp.Sites.ResponseOfUsers5pAuinzC Remove(string id, string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISitesService/Remove", ReplyAction="http://tempuri.org/ISitesService/RemoveResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfUsers5pAuinzC> RemoveAsync(string id, string pid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISitesServiceChannel : AnalyticsApp.Sites.ISitesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SitesServiceClient : System.ServiceModel.ClientBase<AnalyticsApp.Sites.ISitesService>, AnalyticsApp.Sites.ISitesService {
        
        public SitesServiceClient() {
        }
        
        public SitesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SitesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AnalyticsApp.Sites.ResponseOfUsers5pAuinzC Save(string id) {
            return base.Channel.Save(id);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfUsers5pAuinzC> SaveAsync(string id) {
            return base.Channel.SaveAsync(id);
        }
        
        public AnalyticsApp.Sites.ResponseOfSites5pAuinzC GetAll(string id) {
            return base.Channel.GetAll(id);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfSites5pAuinzC> GetAllAsync(string id) {
            return base.Channel.GetAllAsync(id);
        }
        
        public AnalyticsApp.Sites.ResponseOfSites5pAuinzC Get(string id, string pid) {
            return base.Channel.Get(id, pid);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfSites5pAuinzC> GetAsync(string id, string pid) {
            return base.Channel.GetAsync(id, pid);
        }
        
        public AnalyticsApp.Sites.ResponseOfSites5pAuinzC Update(string id, string pid) {
            return base.Channel.Update(id, pid);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfSites5pAuinzC> UpdateAsync(string id, string pid) {
            return base.Channel.UpdateAsync(id, pid);
        }
        
        public AnalyticsApp.Sites.ResponseOfUsers5pAuinzC Remove(string id, string pid) {
            return base.Channel.Remove(id, pid);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Sites.ResponseOfUsers5pAuinzC> RemoveAsync(string id, string pid) {
            return base.Channel.RemoveAsync(id, pid);
        }
    }
}
