//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsApp.Users {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfUsers5pAuinzC", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class ResponseOfUsers5pAuinzC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Users.Error errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnalyticsApp.Users.Users[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AnalyticsApp.Users.Error error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AnalyticsApp.Users.Users[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/AnalyticsServer.Models")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.display_nameField, value) != true)) {
                    this.display_nameField = value;
                    this.RaisePropertyChanged("display_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Guid user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Users.IUsersService")]
    public interface IUsersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Save", ReplyAction="http://tempuri.org/IUsersService/SaveResponse")]
        AnalyticsApp.Users.ResponseOfUsers5pAuinzC Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Save", ReplyAction="http://tempuri.org/IUsersService/SaveResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Get", ReplyAction="http://tempuri.org/IUsersService/GetResponse")]
        AnalyticsApp.Users.ResponseOfUsers5pAuinzC Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Get", ReplyAction="http://tempuri.org/IUsersService/GetResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Remove", ReplyAction="http://tempuri.org/IUsersService/RemoveResponse")]
        AnalyticsApp.Users.ResponseOfUsers5pAuinzC Remove(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Remove", ReplyAction="http://tempuri.org/IUsersService/RemoveResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> RemoveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Update", ReplyAction="http://tempuri.org/IUsersService/UpdateResponse")]
        AnalyticsApp.Users.ResponseOfUsers5pAuinzC Update(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Update", ReplyAction="http://tempuri.org/IUsersService/UpdateResponse")]
        System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> UpdateAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceChannel : AnalyticsApp.Users.IUsersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceClient : System.ServiceModel.ClientBase<AnalyticsApp.Users.IUsersService>, AnalyticsApp.Users.IUsersService {
        
        public UsersServiceClient() {
        }
        
        public UsersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AnalyticsApp.Users.ResponseOfUsers5pAuinzC Save() {
            return base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public AnalyticsApp.Users.ResponseOfUsers5pAuinzC Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public AnalyticsApp.Users.ResponseOfUsers5pAuinzC Remove(string id) {
            return base.Channel.Remove(id);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> RemoveAsync(string id) {
            return base.Channel.RemoveAsync(id);
        }
        
        public AnalyticsApp.Users.ResponseOfUsers5pAuinzC Update(string id) {
            return base.Channel.Update(id);
        }
        
        public System.Threading.Tasks.Task<AnalyticsApp.Users.ResponseOfUsers5pAuinzC> UpdateAsync(string id) {
            return base.Channel.UpdateAsync(id);
        }
    }
}
